### ISSUE TITLE
Not able to see features after installing insomnia-plugin-run-folder

### ISSUE THREAD

**Issue by tanujapatel** [LunaticoCR/insomnia-plugin-run-folder#4]
I have installed insomnia-plugin-run-folder using npm command , but I am not getting any option to run the folder.

**Comment by LunaticoCR** [comment]
> I have installed insomnia-plugin-run-folder using npm command , but I am not getting any option to run the folder.

That's because you need to install it from within the Insomnia app. Go to settings -> plugins.

**Comment by tanujapatel** [comment]
I am trying to install plug-in from app but it’s failing with no deprecation issue

**Comment by tanujapatel** [comment]
Hi,
I am using insomnia 6.3.2
Is this plugin compatible with insomnia 6.3.2?
If not then is there any work around?

**Comment by LunaticoCR** [comment]
I'm not sure about that version, try with the latest version, it works there for sure, I just tried it.
This is the version I have installed:
![image](https://user-images.githubusercontent.com/2124383/129532999-39102b6b-00c4-4463-81ba-74ab5533f60c.png)

And you install it by opening Preferences, in the Plugins tab, like so:
![image](https://user-images.githubusercontent.com/2124383/129533130-fba43e3d-fe65-4712-ba94-96bc7e93df41.png)
