### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by TravisC671** [LunaticoCR/insomnia-plugin-run-folder#5]
Here is what I am getting, it's weird though, cause looking at the code, I do see a license field
![image](https://user-images.githubusercontent.com/63769252/141375339-f979e57f-7fad-4e39-b144-126b672d4774.png)

**Comment by LunaticoCR** [comment]
That's strange. Looking at that stack trace seems like you're on the latest version 2021.6.0 and you're on Windows. I just successfully installed the plugin on the same version of Insomnia but on macOS. Sounds more like an app issue than the plugin. I'd suggest you report it directly with the Insomnia devs at https://docs.insomnia.rest/ using the Help button at the bottom right of the page.

**Comment by neotan** [comment]
In case someone ran into a similar case on Windows 10, stated my working installation here FYR.

Go to menu **Application** > **Preferences**
![image](https://user-images.githubusercontent.com/10399087/185500011-afdd3015-5e00-46a3-b750-f327642fc79b.png)

The plugins folder will be revealed
![image](https://user-images.githubusercontent.com/10399087/185500770-96d9fef8-4877-4949-88a5-8d40a07152ee.png)

Now you good to go ))
![image](https://user-images.githubusercontent.com/10399087/185501103-fbb1c630-93ad-468f-8375-bc1d4566d5d2.png)
